[phases.setup]
nixPkgs = ["nodejs_18", "caddy"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build", "cp Caddyfile /tmp/Caddyfile"]

[staticAssets]
directory = "dist"

[start]
cmd = "caddy run --config /app/Caddyfile --adapter caddyfile"
